- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - add_host:
        name: "{{ item }}"
        groups: limited_selection
      loop:  "{{ (groups['servers'] | shuffle)[0:3] }}"
- hosts: limited_selection
  vars:
     package: vim
  tasks:
     - name: Pull an image opencanary
       community.general.docker_image:
          name: tvh0711/opencanaryv2:latest
          source: pull

     - name: Restart a container opencanary
       community.general.docker_container:
         name: myapplication
         image: tvh0711/opencanaryv2:latest
         state: started
         restart: yes
         #links:
         # - "tvh0711/thesis:v1"
         devices:
          - "/dev/sda:/dev/xvda:rwm"
         ports:
          # Publish container port 9000 as host port 8080
          - "80:80"
          # Publish container UDP port 9001 as host port 8081 on interface 127.0.0.1
          #- "127.0.0.1:8081:9001/udp"
          # Publish container port 9002 as a random host port
          #- "9002"
          # Publish container port 9003 as a free host port in range 8000-8100
          # (the host port will be selected by the Docker daemon)
          #- "8000-8100:9003"
          # Publish container ports 9010-9020 to host ports 7000-7010
          #- "7000-7010:9010-9020"
         env:
             SECRET_KEY: "ssssh"
             # Values which might be parsed as numbers, booleans or other types by the YAML parser need to be quoted
             BOOLEAN_KEY: "yes"




